// type convertion

let datatype = false;
let datachange = Number(datatype);
console.log(datachange);

let datatype1 = typeof null;
console.log(datatype1);

let datatype2  = typeof 1;
console.log(datatype2);

let datatype3 = typeof "vivek";
console.log(datatype3);

let datatype4 = typeof undefined;
console.log(datatype4);

let datatype5 = typeof false;
console.log(datatype5);


let  datatype6  = 0;
let  datachange6 = Boolean(datatype6);
console.log(datachange6);

let  datatype7 = 1;
let  datachange7 = Boolean(datatype7);
console.log(datachange7);

let datatype8 = "type";
let  datachange8 = Number(datatype8);
console.log(datachange8);

let datatype9  = 1;
let datachange9 = String(datatype9);
console.log(datachange9);