// What is javascript

/*
JavaScript is a dynamic computer programming language.
It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.
Complementary to and integrated with HTML.
Open and cross-platform
*/

// JavaScript Values
// The JavaScript syntax defines two types of values;
 
// Fixed values are called Literals.
// Variable values are called Variables.

//Using console in javascript

{
    const boxx = 60; 
     console.log(boxx);
     document.write(boxx + "<br>");
     window.alert(boxx);    
     var box = 800;

// var variable type / box variable name / = assignement / 60 assiged values

    console.log(box);
    console.log("hello javascript");
    console.log(80);
    var Box=70;
    var box=50;
    console.log(Box);
}

// javascript language case-sensitive 

// variable useing var() in javascript

{
    var names="brinza";
    names="Css";
    console.log(names);
    console.log(names);
    
    var Names="foo";
    var names="Javascript";
    console.log(Names);
    
    var thisis=15;
    var thatis=45;
    console.log(thisis-thatis);
    
    var box1="toys";
    var box1="cloths";
    console.log(box1);
}

// new html element add in though javascript

{
    // var newelement=document.createElement("h1");
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);
    
    // var newelement=document.createElement("marquee" , Option);
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);
    
    // var newelement=document.createElement("p");
    // newelement.textContent="how are you!";
    // document.body.appendChild(newelement);
}


//Using the DOM API

{
    var a=50;
    var b="Hey, I Am Javascript";
    // var b=30;
    document.getElementById("demo1").innerHTML=b;
}
document.getElementById("demo2").innerHTML=b;

//let variable ( blockscope variables)

{
    let boxx1="toys1";
     boxx1="clothes";
    document.getElementById("demo3").innerHTML=boxx1;
}

//const variable ( blockscope variables)

{
    const toys="bus";
    document.getElementById("demo4").innerHTML=toys;    
}

document.write('hello javascript!');

{
    const a1=50;
    //console.log(a);
}


// js comments

// single-line comments

/* multi-line 
comments */


// Template literals

// var nameone = "hello";
// var nametwo = 'vivek';
// alert(`${nameone} ${nametwo}`); 


/*  

Name must start with a letter (a to z or A to Z), underscore( _ ), or dollar( $ ) sign. After first letter we can use digits (0 to 9), for example value1. JavaScript variables are case sensitive, for example x and X are different variables.

*/





